CREATE TABLE dbo.DIM_CALENDAR (
    WEEK        VARCHAR(5)   NOT NULL,      -- '01-21', '34-22', etc.
    YEAR        INT          NOT NULL,
    MONTH       TINYINT      NOT NULL,
    WEEK_NUMBER TINYINT      NOT NULL,
    [DATE]      DATE         NOT NULL,
    CONSTRAINT PK_DIM_CALENDAR PRIMARY KEY (WEEK)
);
GO

CREATE TABLE dbo.DIM_CATEGORY (
    ID_CATEGORY INT            NOT NULL,
    CATEGORY    NVARCHAR(100)  NOT NULL,
    CONSTRAINT PK_DIM_CATEGORY PRIMARY KEY (ID_CATEGORY)
);
GO

CREATE TABLE dbo.DIM_SEGMENT (
    CATEGORY   INT           NOT NULL,
    ATTR1      NVARCHAR(50)  NULL,
    ATTR2      NVARCHAR(50)  NULL,
    ATTR3      NVARCHAR(50)  NULL,
    FORMAT     NVARCHAR(50)  NULL,
    SEGMENT    NVARCHAR(50)  NULL
);
GO

CREATE TABLE dbo.DIM_PRODUCT (
    MANUFACTURER     NVARCHAR(100)  NOT NULL,
    BRAND            NVARCHAR(100)  NOT NULL,
    ITEM             VARCHAR(50)    NOT NULL,
    ITEM_DESCRIPTION NVARCHAR(255)  NOT NULL,
    CATEGORY         INT            NOT NULL,
    FORMAT           NVARCHAR(50)   NULL,
    ATTR1            NVARCHAR(50)   NULL,
    ATTR2            NVARCHAR(50)   NULL,
    ATTR3            NVARCHAR(50)   NULL
);
GO


CREATE TABLE dbo.FACT_SALES_STG (
    WEEK                         NVARCHAR(20)  NULL,
    ITEM_CODE                    NVARCHAR(50)  NULL,
    TOTAL_UNIT_SALES_STR         NVARCHAR(50)  NULL,
    TOTAL_VALUE_SALES_STR        NVARCHAR(50)  NULL,
    TOTAL_UNIT_AVG_WEEKLY_STR    NVARCHAR(50)  NULL,
    REGION                       NVARCHAR(100) NULL
);
GO

CREATE TABLE dbo.FACT_SALES (
    WEEK                         VARCHAR(10)    NOT NULL,
    ITEM_CODE                    VARCHAR(50)    NOT NULL,
    TOTAL_UNIT_SALES             DECIMAL(18,4)  NOT NULL,
    TOTAL_VALUE_SALES            DECIMAL(18,4)  NOT NULL,
    TOTAL_UNIT_AVG_WEEKLY_SALES  DECIMAL(18,4)  NOT NULL,
    REGION                       NVARCHAR(100)  NOT NULL
);
GO
